### ISSUE TITLE
Global logout plugin trigger saml sp logout cycle

### ISSUE THREAD

**Issue by whlsxl** [LemonLDAPNG/lemonldap-ng#3]
When the `"globalLogoutRule": 1` is set, the SAML SP logout button will redirect to the portal page. However, the portal does not log out; instead, it redirects back to the SAML SP and  log in again.

Furthermore, setting `globalLogoutRule=1` will not trigger SAML logout when the portal page logs out.

**Comment by coudot** [comment]
Please report on OW2 tracker

**Comment by whlsxl** [comment]
I wish I could, but the membership of ow2 is still pending.

**Comment by amottier** [comment]
> I wish I could, but the membership of ow2 is still pending.

@whlsxl sorry about that. As the description for account creation was limited to "report bugs" we falsely assume it was a spammer account (we have a lot of them lately). I just sent you the email to allow you to activate your account.

**Comment by whlsxl** [comment]
Thanks!
